# This is the production docker compose file without the --reload, bind and with no-hardcoded EV's.
version : "3"


services:
  api:
    image: anant9796/fastapi 
    depends_on: 
      - postgres
    ports:
        - 80:8000   # Portt 80 so that we can use our web browser.
    # volumes: # This is a bind mount which allows us to sync the folders of our dev environment and docker containers
    #   - ./:/usr/src/app:ro      # folders of our current directory:folder structure in ur docker cotainer. The ro(read_only prevents the container from changing any of the files)
    # command : uvicorn app.main:app --host 0.0.0.0 --port 8000
      # env_file:
          # - ./.env
    environment:
        - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}   # To reference an EV we do ${EV} and its gonna look for EV on the linux machine the container runs on.
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - DATABASE_NAME=${DATABASE_NAME}
        - DATABASE_USERNAME=${DATABASE_USERNAME}
        - SECRET_KEY=${SECRET_KEY}
        - ALGORITHM=${ALGORITHM}
        - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:

